# Generated by Django 6.0.5 on 2026-09-21 17:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Unique identifier used by the application, e.g. course_enrollment_learning_goals.', max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Email content')),
                ('body_text', models.TextField(blank=True, help_text='Optional plain-text version of the email.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
