# Generated by Django 6.0.5 on 2026-09-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.SlugField(blank=True, help_text='Generated automatically from the template name.', max_length=100, unique=True),
        ),
    ]
