# Generated by Django 6.0.5 on 2026-09-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_emailtemplate_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='heading',
            field=models.CharField(blank=True, help_text='Heading displayed inside the email.', max_length=255),
        ),
    ]
