# Generated by Django 6.0.5 on 2026-09-22 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_emailtemplate_heading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('active', 'Active'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('placement_test', 'Placement test'), ('website', 'Website subscription'), ('account', 'Account preferences')], default='placement_test', max_length=30)),
                ('consent_text', models.TextField(blank=True, help_text='Exact marketing consent wording presented to the subscriber.')),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing subscriber',
                'verbose_name_plural': 'Marketing subscribers',
                'ordering': ['email'],
            },
        ),
    ]
