# Generated by Django 6.0.5 on 2026-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_learneraccountclosurenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='learneraccountclosurenotice',
            name='effective_closure_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Earliest permitted closure time, accounting for the 30-day notice period.', null=True),
        ),
    ]
