# Generated by Django 6.0.5 on 2026-05-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_company_rename_default_country_userprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='learning_goals',
        ),
    ]
