# Generated by Django 6.0.5 on 2026-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_learning_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual Student'), ('company_admin', 'Company Admin'), ('employee', 'Employee')], default='individual', max_length=20),
        ),
    ]
