# Generated by Django 6.0.5 on 2026-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.CharField(choices=[('Pending', 'Pending'), ('A1 Beginner', 'A1 Beginner'), ('A2 Elementary', 'A2 Elementary'), ('B1 Pre-Intermediate', 'B1 Pre-Intermediate'), ('B2.1 Low Intermediate', 'B2.1 Low Intermediate'), ('B2.2 High Intermediate', 'B2.2 High Intermediate'), ('C1.1 Low Advance', 'C1.1 Low Advance'), ('C1.2 High Advance', 'C1.2 High Advance'), ('C2 Proficiency', 'C2 Proficiency')], default='Pending', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual Student'), ('company_admin', 'Company Admin'), ('employee', 'Employee')], default='individual', max_length=30),
        ),
    ]
