# Generated by Django 6.0.5 on 2026-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_level_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='native_language',
            field=models.CharField(blank=True, choices=[('', 'Native language'), ('es', 'Spanish'), ('ca', 'Catalan'), ('en', 'English'), ('fr', 'French'), ('it', 'Italian'), ('de', 'German'), ('pt', 'Portuguese'), ('other', 'Other')], max_length=20),
        ),
    ]
