# Generated by Django 6.0.5 on 2026-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_native_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='native_language',
            field=models.CharField(blank=True, choices=[('', 'Native language'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('de', 'German'), ('pt', 'Portuguese'), ('other', 'Other')], max_length=20),
        ),
    ]
