# Generated by Django 6.0.5 on 2026-05-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofile_native_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('individual', 'Student Profile'), ('company_admin', 'Company Admin'), ('employee', 'Employee')], default='individual', max_length=30),
        ),
    ]
