# Generated by Django 6.0.5 on 2026-05-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_userprofile_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='level',
            new_name='current_level',
        ),
    ]
