# Generated by Django 6.0.5 on 2026-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_rename_level_userprofile_current_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('A1 Beginner', 'A1 Beginner'), ('A2 Elementary', 'A2 Elementary'), ('B1.1 Pre-Intermediate', 'B1.1 Pre-Intermediate'), ('B1.2 Low Intermediate', 'B1.2 Low Intermediate'), ('B2.1 Intermediate', 'B2.1 Intermediate'), ('B2.2 High Intermediate', 'B2.2 High Intermediate'), ('C1.1 Low Advance', 'C1.1 Low Advance'), ('C1.2 High Advance', 'C1.2 High Advance'), ('C2 Proficiency', 'C2 Proficiency')], default='', help_text='Current English level. Only admin should update this.', max_length=200),
        ),
    ]
