# Generated by Django 6.0.5 on 2026-05-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_userprofile_current_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('A1', 'A1 Beginner'), ('A2', 'A2 Elementary'), ('B1.1', 'B1.1 Pre-Intermediate'), ('B1.2', 'B1.2 Low Intermediate'), ('B2.1', 'B2.1 Intermediate'), ('B2.2', 'B2.2 High Intermediate'), ('C1.1', 'C1.1 Low Advance'), ('C1.2', 'C1.2 High Advance'), ('C2', 'C2 Proficiency')], default='', help_text='Current English level. Only admin should update this.', max_length=200),
        ),
    ]
