# Generated by Django 6.0.5 on 2026-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_userprofile_current_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default_profile.png', null=True, upload_to='profile_photos/'),
        ),
    ]
