# Generated by Django 6.0.5 on 2026-06-25 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('A1', 'A1 Beginner'), ('A2', 'A2 Elementary'), ('B1.1', 'B1.1 Pre-Intermediate'), ('B1.2', 'B1.2 Low Intermediate'), ('B2.1', 'B2.1 Intermediate'), ('B2.2', 'B2.2 High Intermediate'), ('C1.1', 'C1.1 Low Advance'), ('C1.2', 'C1.2 High Advance'), ('C2', 'C2 Proficiency')], max_length=10, null=True)),
                ('target_level', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('A1', 'A1 Beginner'), ('A2', 'A2 Elementary'), ('B1.1', 'B1.1 Pre-Intermediate'), ('B1.2', 'B1.2 Low Intermediate'), ('B2.1', 'B2.1 Intermediate'), ('B2.2', 'B2.2 High Intermediate'), ('C1.1', 'C1.1 Low Advance'), ('C1.2', 'C1.2 High Advance'), ('C2', 'C2 Proficiency')], max_length=10, null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('teacher_notes', models.TextField(blank=True)),
                ('participation', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_support', 'Needs Support')], max_length=20, null=True)),
                ('risk_status', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_goals', models.ManyToManyField(blank=True, related_name='student_academic_profiles', to='profiles.learninggoal')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
