# Generated by Django 6.0.5 on 2026-06-25 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_class_duration_source_and_more'),
        ('profiles', '0018_learninggoal_studentacademicprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening')], max_length=20)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('developing', 'Developing'), ('proficient', 'Proficient'), ('advanced', 'Advanced')], default='developing', max_length=20)),
                ('strengths', models.TextField(blank=True)),
                ('needs_work', models.TextField(blank=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skill_assessments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['skill'],
                'unique_together': {('student', 'course', 'skill')},
            },
        ),
    ]
