# Generated by Django 6.0.5 on 2026-06-25 19:58

import json
from django.db import migrations, models


def convert_skill_text_fields_to_json(apps, schema_editor):
    StudentSkillAssessment = apps.get_model(
        "profiles",
        "StudentSkillAssessment"
    )

    for assessment in StudentSkillAssessment.objects.all():
        for field_name in ["strengths", "needs_work"]:
            value = getattr(assessment, field_name)

            if not value:
                json_value = json.dumps([])
            elif isinstance(value, list):
                json_value = json.dumps(value)
            else:
                json_value = json.dumps([
                    item.strip()
                    for item in str(value).splitlines()
                    if item.strip()
                ])

            setattr(assessment, field_name, json_value)

        assessment.save(update_fields=["strengths", "needs_work"])


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_studentskillassessment"),
    ]

    operations = [
        migrations.RunPython(
            convert_skill_text_fields_to_json,
            migrations.RunPython.noop,
        ),

        migrations.RemoveField(
            model_name="studentskillassessment",
            name="level",
        ),

        migrations.AddField(
            model_name="studentskillassessment",
            name="rating",
            field=models.CharField(
                choices=[
                    ("needs_work", "Needs Work"),
                    ("developing", "Developing"),
                    ("secure", "Secure"),
                    ("strong", "Strong"),
                ],
                default="developing",
                max_length=20,
            ),
        ),

        migrations.AlterField(
            model_name="studentskillassessment",
            name="needs_work",
            field=models.JSONField(blank=True, default=list),
        ),

        migrations.AlterField(
            model_name="studentskillassessment",
            name="strengths",
            field=models.JSONField(blank=True, default=list),
        ),
    ]