# Generated by Django 6.0.5 on 2026-06-25 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_studentskillassessment_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentskillassessment',
            options={},
        ),
        migrations.RemoveField(
            model_name='studentskillassessment',
            name='needs_work',
        ),
        migrations.RemoveField(
            model_name='studentskillassessment',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='studentskillassessment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='studentskillassessment',
            name='strengths',
        ),
        migrations.CreateModel(
            name='StudentSubSkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subskill', models.CharField(choices=[('speaking_range', 'Range'), ('speaking_fluency', 'Fluency'), ('speaking_accuracy', 'Accuracy'), ('speaking_pronunciation', 'Pronunciation & Intonation'), ('speaking_interaction', 'Interaction'), ('reading_scanning', 'Scanning'), ('reading_skimming', 'Skimming'), ('reading_comprehension', 'Reading Comprehension'), ('listening_gist', 'Listening for Gist'), ('listening_specific_info', 'Listening for Specific Information'), ('listening_detail', 'Listening for Detail'), ('writing_organization', 'Organization'), ('writing_cohesion', 'Cohesion & Coherence'), ('writing_vocab_grammar', 'Vocabulary & Grammar'), ('writing_register', 'Register')], max_length=50)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('rating', models.CharField(choices=[('needs_work', 'Needs Work'), ('developing', 'Developing'), ('secure', 'Secure'), ('strong', 'Strong')], default='developing', max_length=20)),
                ('teacher_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subskill_assessments', to='profiles.studentskillassessment')),
            ],
            options={
                'unique_together': {('skill_assessment', 'subskill')},
            },
        ),
    ]
