# Generated by Django 6.0.5 on 2026-06-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_studentskillassessment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='subskill',
            field=models.CharField(choices=[('speaking', [('range', 'Range'), ('fluency', 'Fluency'), ('accuracy', 'Accuracy'), ('pronunciation', 'Pronunciation & Intonation'), ('interaction', 'Interaction')]), ('reading', [('scanning', 'Scanning'), ('skimming', 'Skimming'), ('reading_comprehension', 'Reading Comprehension')]), ('listening', [('gist', 'Listening for Gist'), ('specific_information', 'Listening for Specific Information'), ('detail', 'Listening for Detail')]), ('writing', [('organization', 'Organization'), ('cohesion', 'Cohesion & Coherence'), ('vocabulary_grammar', 'Vocabulary & Grammar'), ('register', 'Register')])], max_length=50),
        ),
    ]
