# Generated by Django 6.0.5 on 2026-06-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_studentsubskillassessment_subskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='subskill',
            field=models.CharField(choices=[('range', 'Range'), ('fluency', 'Fluency'), ('accuracy', 'Accuracy'), ('pronunciation', 'Pronunciation & Intonation'), ('interaction', 'Interaction'), ('scanning', 'Scanning'), ('skimming', 'Skimming'), ('reading_comprehension', 'Reading Comprehension'), ('gist', 'Listening for Gist'), ('specific_information', 'Listening for Specific Information'), ('detail', 'Listening for Detail'), ('organization', 'Organization'), ('cohesion', 'Cohesion & Coherence'), ('vocabulary_grammar', 'Vocabulary & Grammar'), ('register', 'Register')], max_length=50),
        ),
    ]
