# Generated by Django 6.0.5 on 2026-06-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_studentsubskillassessment_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsubskillassessment',
            options={'ordering': ['subskill']},
        ),
    ]
