# Generated by Django 6.0.5 on 2026-06-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_studentsubskillassessment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='rating',
            field=models.CharField(choices=[('needs_work', 'Needs Work'), ('developing', 'Developing'), ('confident', 'Confident'), ('strong', 'Strong')], default='developing', max_length=20),
        ),
    ]
