# Generated by Django 6.0.5 on 2026-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_alter_studentsubskillassessment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=45, editable=False),
        ),
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='subskill',
            field=models.CharField(choices=[('fluency', 'Fluency'), ('accuracy_and_range', 'Accuracy & Range'), ('pronunciation', 'Pronunciation'), ('interaction', 'Interaction'), ('scanning', 'Scanning - Specific Information'), ('skimming', 'Skimming - Gist (General Idea)'), ('detailed', 'Detailed'), ('gist', 'Gist (General Idea)'), ('specific_information', 'Specific Information'), ('detailed', 'Detailed'), ('organization', 'Organization'), ('cohesion', 'Cohesion & Coherence'), ('vocabulary_grammar', 'Vocabulary & Grammar'), ('register', 'Register')], max_length=50),
        ),
    ]
