# Generated by Django 6.0.5 on 2026-06-26 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_alter_studentsubskillassessment_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='subskill',
            field=models.CharField(choices=[('fluency', 'Fluency'), ('accuracy_and_range', 'Accuracy & Range'), ('pronunciation', 'Pronunciation'), ('interaction', 'Interaction'), ('scanning', 'Scanning - Specific Information'), ('skimming', 'Skimming - Gist (General Idea)'), ('detailed', 'Deep Understanding'), ('gist', 'Gist (General Idea)'), ('specific_information', 'Specific Information'), ('detailed', 'Deep Understanding'), ('organization', 'Organization'), ('cohesion', 'Cohesion & Coherence'), ('vocabulary_grammar', 'Vocabulary & Grammar'), ('register', 'Register')], max_length=50),
        ),
        migrations.CreateModel(
            name='StudentSkillTermSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_label', models.CharField(max_length=50)),
                ('percentage', models.PositiveSmallIntegerField()),
                ('recorded_at', models.DateField(auto_now_add=True)),
                ('skill_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_snapshots', to='profiles.studentskillassessment')),
            ],
            options={
                'ordering': ['recorded_at'],
                'unique_together': {('skill_assessment', 'term_label')},
            },
        ),
    ]
