# Generated by Django 6.0.5 on 2026-06-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_alter_studentsubskillassessment_subskill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubskillassessment',
            name='teacher_notes',
        ),
    ]
