# Generated by Django 6.0.5 on 2026-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_remove_studentsubskillassessment_teacher_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='subskill',
            field=models.CharField(choices=[('fluency', 'Fluency'), ('accuracy_and_range', 'Grammar & vocabulary: Accuracy & range'), ('pronunciation', 'Pronunciation'), ('interaction', 'Interaction'), ('scanning', 'Scanning - Specific Information'), ('skimming', 'Skimming - Gist (General Idea)'), ('detailed', 'Deep Understanding'), ('gist', 'Gist (General Idea)'), ('specific_information', 'Specific Information'), ('detailed', 'Deep Understanding'), ('organization', 'Organization'), ('cohesion', 'Cohesion & Coherence'), ('vocabulary_grammar', 'Vocabulary & Grammar'), ('register', 'Register')], max_length=50),
        ),
    ]
