# Generated by Django 6.0.5 on 2026-07-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_alter_studentsubskillassessment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='rating',
            field=models.CharField(choices=[('needs_work', 'Needs Work'), ('developing', 'Developing'), ('passing', 'Passing'), ('confident', 'Confident'), ('strong', 'Strong')], default='developing', max_length=20),
        ),
    ]
