# Generated by Django 6.0.5 on 2026-07-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_alter_studentsubskillassessment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='rating',
            field=models.CharField(choices=[('needs_work', 'Needs Work'), ('developing', 'Developing'), ('passing', 'Pass'), ('confident', 'Confident'), ('strong', 'Strong')], default='developing', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='subskill',
            field=models.CharField(choices=[('fluency', 'Fluency'), ('accuracy_and_range', 'Grammar & vocabulary: Accuracy & range'), ('pronunciation', 'Pronunciation'), ('interaction', 'Interaction'), ('scanning', 'Scanning: Specific information'), ('skimming', 'Skimming (Gist): General Idea'), ('detailed', 'In detail: Deep Understanding'), ('gist', 'For Gist: General Idea'), ('specific_information', 'Specific Information'), ('detailed', 'In detail: Deep Understanding'), ('organization', 'Organization'), ('cohesion', 'Cohesion & Coherence'), ('vocabulary_grammar', 'Vocabulary & Grammar'), ('register', 'Register')], max_length=50),
        ),
    ]
