# Generated by Django 6.0.5 on 2026-08-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_alter_studentsubskillassessment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('learner', 'Student Profile'), ('company_admin', 'Company Admin'), ('employee', 'Employee')], default='learner', max_length=30),
        ),
    ]
