# Generated by Django 6.0.5 on 2026-08-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_alter_studentacademicprofile_current_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=50, editable=False),
        ),
    ]
