# Generated by Django 6.0.5 on 2026-08-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_alter_studentsubskillassessment_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='subskill',
            field=models.CharField(choices=[('fluency', 'Fluency'), ('accuracy_and_range', 'Grammar & vocabulary (Accuracy & range)'), ('pronunciation', 'Pronunciation'), ('interaction', 'Interaction'), ('scanning', 'Scanning (Specific information)'), ('skimming', 'Skimming (General Idea)'), ('detailed', 'In detail (Deep Understanding)'), ('gist', 'Gist (General Idea)'), ('specific_information', 'Specific Information'), ('detailed', 'In detail (Deep Understanding)'), ('organization', 'Structure & Organization'), ('cohesion', 'Cohesion & Coherence'), ('vocabulary_grammar', 'Grammar & vocabulary (Accuracy & range)'), ('register', 'Register (Style accuracy)')], max_length=50),
        ),
    ]
