# Generated by Django 6.0.5 on 2026-08-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_alter_studentsubskillassessment_subskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='rating',
            field=models.CharField(choices=[('needs_work', 'Needs Work'), ('developing', 'Developing'), ('pass', 'Pass'), ('confident', 'Confident'), ('strong', 'Strong')], default='developing', max_length=20),
        ),
    ]
