# Generated by Django 6.0.5 on 2026-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_alter_studentsubskillassessment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='rating',
            field=models.CharField(choices=[('needs_work', 'Needs Work'), ('developing', 'Developing'), ('minimum_level_requirements', 'Minimum level requirements'), ('confident', 'Confident'), ('strong', 'Strong')], default='developing', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='subskill',
            field=models.CharField(choices=[('fluency', 'Fluency'), ('accuracy_and_range', 'Grammar & vocabulary (Accuracy & range)'), ('pronunciation', 'Pronunciation'), ('interaction', 'Interaction'), ('scanning', 'Scanning (Specific information)'), ('skimming', 'Skimming (General Idea)'), ('detailed', 'In detail (Deep Understanding)'), ('gist', 'For Gist (General Idea)'), ('specific_information', 'For Specific Information'), ('detailed', 'In detail (Deep Understanding)'), ('organization', 'Structure & Organization'), ('cohesion', 'Cohesion & Coherence'), ('vocabulary_grammar', 'Grammar & vocabulary (Accuracy & range)'), ('register', 'Register (Style accuracy)')], max_length=50),
        ),
    ]
