# Generated by Django 6.0.5 on 2026-08-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_alter_studentsubskillassessment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='rating',
            field=models.CharField(choices=[('needs_work', 'Needs Work'), ('developing', 'Developing'), ('minimum_level_requirements', 'Minimum level requirements (pass)'), ('confident', 'Confident'), ('strong', 'Strong')], default='developing', max_length=30),
        ),
    ]
