# Generated by Django 6.0.5 on 2026-08-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_alter_studentsubskillassessment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubskillassessment',
            name='percentage',
        ),
        migrations.AddField(
            model_name='studentskilltermsnapshot',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
