# Generated by Django 6.0.5 on 2026-08-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_remove_studentsubskillassessment_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentskilltermsnapshot',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='studentskilltermsnapshot',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
