# Generated by Django 6.0.5 on 2026-08-15 00:18

from decimal import Decimal

from django.db import migrations, models


def convert_percentage_to_score(apps, schema_editor):
    """
    Convert existing StudentSkillTermSnapshot percentage values
    to the new /10 score system.

    Examples:
        38  -> 3.8
        50  -> 5.0
        75  -> 7.5
        100 -> 10.0
    """

    StudentSkillTermSnapshot = apps.get_model(
        "profiles",
        "StudentSkillTermSnapshot",
    )

    for snapshot in StudentSkillTermSnapshot.objects.all():
        if snapshot.percentage is not None:
            snapshot.score = (
                Decimal(str(snapshot.percentage))
                / Decimal("10")
            )

            snapshot.save(
                update_fields=["score"]
            )


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0041_remove_studentsubskillassessment_percentage_and_more",
        ),
    ]

    operations = [

        # -----------------------------------------------------
        # 1. CONVERT EXISTING HISTORICAL DATA
        #
        # At this point:
        # - percentage still exists
        # - score exists and allows NULL
        # -----------------------------------------------------
        migrations.RunPython(
            convert_percentage_to_score,
            migrations.RunPython.noop,
        ),

        # -----------------------------------------------------
        # 2. REMOVE OLD PERCENTAGE FIELD
        # -----------------------------------------------------
        migrations.RemoveField(
            model_name="studentskilltermsnapshot",
            name="percentage",
        ),

        # -----------------------------------------------------
        # 3. MAKE SCORE NON-NULLABLE
        #
        # Safe now because all existing percentage values
        # have been converted into score values.
        # -----------------------------------------------------
        migrations.AlterField(
            model_name="studentskilltermsnapshot",
            name="score",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
            ),
        ),
    ]