# Generated by Django 6.0.5 on 2026-08-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_remove_studentskilltermsnapshot_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='rating',
            field=models.CharField(choices=[('needs_work', 'Priority areas'), ('developing', 'Developing areas'), ('required_standard', 'Required standard achieved'), ('confident', 'Confident areas'), ('strong', 'Key strengths')], default='developing', max_length=30),
        ),
    ]
