# Generated by Django 6.0.5 on 2026-08-15 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_alter_studentsubskillassessment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='rating',
            field=models.CharField(blank=True, choices=[('needs_work', 'Priority areas'), ('developing', 'Developing areas'), ('required_standard', 'Required standard achieved'), ('confident', 'Confident areas'), ('strong', 'Key strengths')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='StudentSkillAssessmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('skill_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_snapshots', to='profiles.studentskillassessment')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
