# Generated by Django 6.0.5 on 2026-08-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_alter_studentsubskillassessment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubskillassessment',
            name='rating',
            field=models.CharField(blank=True, choices=[('needs_work', 'Focus areas'), ('developing', 'Developing'), ('required_standard', 'Required standard achieved'), ('confident', 'Confident in'), ('strong', 'Key strengths')], max_length=30, null=True),
        ),
    ]
