# Generated by Django 6.0.5 on 2026-08-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_alter_studentsubskillassessment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('individual_learner', 'Individual Learner'), ('company_admin', 'Company Admin'), ('employee', 'Employee')], default='individual_learner', max_length=30),
        ),
    ]
