# Generated by Django 6.0.5 on 2026-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicprofile',
            name='current_level',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1.1', 'B1.1 - Pre-Intermediate'), ('B1.2', 'B1.2 - Lower Intermediate'), ('B2.1', 'B2.1 - Intermediate'), ('B2.2', 'B2.2 - Higher Intermediate'), ('C1.1', 'C1.1 - Lower Advanced'), ('C1.2', 'C1.2 - Higher Advanced'), ('C2', 'C2 Proficiency')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademicprofile',
            name='target_level',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1.1', 'B1.1 - Pre-Intermediate'), ('B1.2', 'B1.2 - Lower Intermediate'), ('B2.1', 'B2.1 - Intermediate'), ('B2.2', 'B2.2 - Higher Intermediate'), ('C1.1', 'C1.1 - Lower Advanced'), ('C1.2', 'C1.2 - Higher Advanced'), ('C2', 'C2 Proficiency')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1.1', 'B1.1 - Pre-Intermediate'), ('B1.2', 'B1.2 - Lower Intermediate'), ('B2.1', 'B2.1 - Intermediate'), ('B2.2', 'B2.2 - Higher Intermediate'), ('C1.1', 'C1.1 - Lower Advanced'), ('C1.2', 'C1.2 - Higher Advanced'), ('C2', 'C2 Proficiency')], default='', help_text='Current English level. Only admin should update this.', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('learner', 'Learner'), ('company_admin', 'Company Admin'), ('employee', 'Employee')], default='learner', max_length=30),
        ),
    ]
