# Generated by Django 6.0.5 on 2026-09-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_alter_studentacademicprofile_current_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentacademicprofile',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='studentacademicprofile',
            name='participation',
        ),
        migrations.RemoveField(
            model_name='studentacademicprofile',
            name='risk_status',
        ),
        migrations.RemoveField(
            model_name='studentacademicprofile',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='studentacademicprofile',
            name='target_level',
        ),
        migrations.RemoveField(
            model_name='studentacademicprofile',
            name='teacher_notes',
        ),
        migrations.RemoveField(
            model_name='studentacademicprofile',
            name='weaknesses',
        ),
    ]
