# Generated by Django 6.0.5 on 2026-09-17 22:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_delete_studentneedsanalysis'),
        ('profiles', '0048_remove_studentacademicprofile_current_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNeedsAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('english_use_frequency', models.CharField(blank=True, max_length=30)),
                ('communication_situations', models.JSONField(blank=True, default=list)),
                ('communication_partners', models.JSONField(blank=True, default=list)),
                ('speaking_confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('listening_confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reading_confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('writing_confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('biggest_challenges', models.TextField(blank=True)),
                ('priority_areas', models.JSONField(blank=True, default=list)),
                ('course_goal', models.TextField(blank=True)),
                ('learning_preferences', models.JSONField(blank=True, default=list)),
                ('correction_preference', models.CharField(blank=True, max_length=30)),
                ('self_study_time', models.CharField(blank=True, max_length=30)),
                ('preferred_topics', models.TextField(blank=True)),
                ('additional_information', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='needs_analysis', to='courses.courseenrollment')),
            ],
            options={
                'verbose_name': 'Student needs analysis',
                'verbose_name_plural': 'Student needs analysis',
            },
        ),
    ]
