# Generated by Django 6.0.5 on 2026-09-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_studentneedsanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentneedsanalysis',
            name='accent_exposure',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentneedsanalysis',
            name='accent_exposure_other',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
