# Generated by Django 6.0.5 on 2026-09-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_studentneedsanalysis_accent_exposure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentneedsanalysis',
            name='biggest_challenges',
        ),
    ]
