# Generated by Django 6.0.5 on 2026-09-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0051_remove_studentneedsanalysis_biggest_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentneedsanalysis',
            name='correction_preference',
        ),
    ]
