# Generated by Django 6.0.5 on 2026-09-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_remove_studentneedsanalysis_correction_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentneedsanalysis',
            name='self_study_time',
        ),
    ]
