# Generated by Django 6.0.5 on 2026-09-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_remove_studentneedsanalysis_course_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentneedsanalysis',
            name='learning_preferences',
        ),
        migrations.RemoveField(
            model_name='studentneedsanalysis',
            name='preferred_topics',
        ),
    ]
