# Generated by Django 6.0.5 on 2026-09-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_remove_studentneedsanalysis_learning_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentacademicprofile',
            name='learning_goals',
        ),
        migrations.DeleteModel(
            name='LearningGoal',
        ),
    ]
