# Generated by Django 6.0.5 on 2026-09-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_remove_studentacademicprofile_learning_goals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentskillassessment',
            name='teacher_notes',
        ),
    ]
