# Generated by Django 6.0.5 on 2026-09-27 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0058_studenttermassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermSubSkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subskill', models.CharField(choices=[('fluency', 'Fluency'), ('accuracy_and_range', 'Grammar & vocabulary (Accuracy & range)'), ('pronunciation', 'Pronunciation'), ('interaction', 'Interaction'), ('scanning', 'Scanning (Specific information)'), ('skimming', 'Skimming (General Idea)'), ('detailed', 'In detail (Deep Understanding)'), ('gist', 'For Gist (General Idea)'), ('specific_information', 'For Specific Information'), ('detailed', 'In detail (Deep Understanding)'), ('organization', 'Structure & Organization'), ('cohesion', 'Cohesion & Coherence'), ('vocabulary_grammar', 'Grammar & vocabulary (Accuracy & range)'), ('register', 'Register (Style accuracy)')], max_length=50)),
                ('rating', models.CharField(blank=True, choices=[('needs_work', 'Focus areas'), ('developing', 'Developing'), ('required_standard', 'Required standard achieved'), ('confident', 'Confident in'), ('strong', 'Key strengths')], max_length=30, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subskill'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentskilltermsnapshot',
            options={'ordering': ['skill']},
        ),
        migrations.AlterUniqueTogether(
            name='studentskilltermsnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentskilltermsnapshot',
            name='skill',
            field=models.CharField(blank=True, choices=[('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentskilltermsnapshot',
            name='term_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='profiles.studenttermassessment'),
        ),
        migrations.AlterField(
            model_name='studentskilltermsnapshot',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddConstraint(
            model_name='studentskilltermsnapshot',
            constraint=models.UniqueConstraint(fields=('term_assessment', 'skill'), name='unique_skill_per_term_assessment'),
        ),
        migrations.AddField(
            model_name='studenttermsubskillassessment',
            name='skill_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subskill_assessments', to='profiles.studentskilltermsnapshot'),
        ),
        migrations.RemoveField(
            model_name='studentskilltermsnapshot',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='studentskilltermsnapshot',
            name='skill_assessment',
        ),
        migrations.RemoveField(
            model_name='studentskilltermsnapshot',
            name='term_label',
        ),
        migrations.AddConstraint(
            model_name='studenttermsubskillassessment',
            constraint=models.UniqueConstraint(fields=('skill_snapshot', 'subskill'), name='unique_subskill_per_term_skill'),
        ),
    ]
