# Generated by Django 6.0.5 on 2026-09-27 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0060_require_term_snapshot_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermAssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(help_text='Snapshot of the generated assessment report.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='profiles.studenttermassessment')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_term_assessment_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Term Assessment Report',
                'verbose_name_plural': 'Student Term Assessment Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
