# Generated by Django 6.0.5 on 2026-09-22 18:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('test_version', models.CharField(default='1.1', max_length=10)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('answer_snapshot', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MaxValueValidator(50)])),
                ('recommended_level', models.CharField(blank=True, choices=[('foundation', 'Foundation / Teacher review'), ('elementary', 'Elementary'), ('pre_intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced')], editable=False, max_length=20)),
                ('cefr_reference', models.CharField(blank=True, editable=False, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.1', max_length=10)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('area', models.CharField(choices=[('grammar', 'Grammar'), ('vocabulary', 'Vocabulary'), ('language_use', 'Language use')], max_length=20)),
                ('language_point', models.CharField(max_length=200)),
                ('target_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['version', 'number'],
                'constraints': [models.UniqueConstraint(fields=('version', 'number'), name='unique_placement_question_per_version')],
            },
        ),
    ]
