# Generated by Django 6.0.5 on 2026-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementquestion',
            name='option_d',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='placementquestion',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
