# Generated by Django 6.0.5 on 2026-09-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_placementquestion_option_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementattempt',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
