# Generated by Django 6.0.5 on 2026-09-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_alter_placementattempt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementattempt',
            name='answer_snapshot',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='placementattempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='placementattempt',
            name='recommended_level',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation / Teacher review'), ('elementary', 'Elementary'), ('pre_intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficiency', 'Proficiency')], editable=False, max_length=20),
        ),
    ]
