# Generated by Django 6.0.5 on 2026-05-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Actual number of hours for this course.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='default_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Default number of hours for this course type.', max_digits=5, null=True),
        ),
    ]
