# Generated by Django 6.0.5 on 2026-05-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_total_hours_coursetype_default_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_duration',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Duration of each class in hours, e.g. 1.0, 1.5 or 2.0.', max_digits=3, null=True),
        ),
    ]
