# Generated by Django 6.0.5 on 2026-05-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursetimetableslot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(fields=('course', 'start_time'), name='unique_course_session_start_time'),
        ),
    ]
