# Generated by Django 6.0.5 on 2026-05-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='class_number',
            field=models.PositiveIntegerField(blank=True, help_text='Lesson number within the course.', null=True),
        ),
    ]
