# Generated by Django 6.0.5 on 2026-05-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_classsession_class_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(help_text='Date of the bank holiday.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active holidays are shown in the calendar.')),
            ],
            options={
                'verbose_name': 'Bank holiday',
                'verbose_name_plural': 'Bank holidays',
                'ordering': ['date'],
            },
        ),
    ]
