# Generated by Django 6.0.5 on 2026-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_bankholiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankholiday',
            options={'ordering': ['start_date'], 'verbose_name': 'Bank holiday', 'verbose_name_plural': 'Bank holidays'},
        ),
        migrations.RemoveField(
            model_name='bankholiday',
            name='date',
        ),
        migrations.AddField(
            model_name='bankholiday',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional. Leave empty for a single-day bank holiday.', null=True),
        ),
        migrations.AddField(
            model_name='bankholiday',
            name='start_date',
            field=models.DateField(blank=True, help_text='First day of the bank holiday.', null=True),
        ),
    ]
