# Generated by Django 6.0.5 on 2026-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_bankholiday_options_remove_bankholiday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
