# Generated by Django 6.0.5 on 2026-06-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='current_level',
            field=models.CharField(blank=True, help_text='Current CEFR level, e.g. B2, C1.', max_length=30),
        ),
    ]
