# Generated by Django 6.0.5 on 2026-06-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_courseenrollment_current_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='current_level',
        ),
        migrations.AddField(
            model_name='course',
            name='current_level',
            field=models.CharField(blank=True, help_text='Current CEFR level, e.g. B2, C1.', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='target_level',
            field=models.CharField(blank=True, help_text='Optional target CEFR level, e.g. B2, C1.', max_length=30),
        ),
    ]
