# Generated by Django 6.0.5 on 2026-06-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_courseenrollment_current_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='target_level',
        ),
    ]
