# Generated by Django 6.0.5 on 2026-06-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_target_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='current_level',
            new_name='course_level',
        ),
    ]
