# Generated by Django 6.0.5 on 2026-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_current_level_course_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_duration_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manually set'), ('auto', 'Calculated from timetable')], help_text='Shows whether class duration was manually set or calculated from timetable slots.', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration of each class in hours, e.g. 1.25, 1.50, 0.75 or 2.00.', max_digits=4, null=True),
        ),
    ]
