# Generated by Django 6.0.5 on 2026-06-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_class_duration_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending_reschedule', 'Pending reschedule'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('attended', 'Attended'), ('missed', 'Missed'), ('excused', 'Excused'), ('cancelled', 'Cancelled'), ('pending_reschedule', 'Pending reschedule')], default='scheduled', max_length=20),
        ),
    ]
