# Generated by Django 6.0.5 on 2026-06-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_classsession_status_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('attended', 'Attended'), ('missed', 'Missed'), ('excused', 'Excused'), ('cancelled', 'Cancelled'), ('pending_reschedule', 'Pending reschedule')], default='scheduled', max_length=30),
        ),
    ]
