# Generated by Django 6.0.5 on 2026-08-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classsession',
            name='unique_course_session_start_time',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('attended', 'Attended'), ('missed', 'Missed'), ('excused', 'Excused')], default='scheduled', max_length=30),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='class_number',
            field=models.PositiveIntegerField(help_text='Lesson number within the course.'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending_reschedule', 'Pending reschedule'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed')], default='scheduled', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(fields=('course', 'class_number'), name='unique_course_class_number'),
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='is_cancelled',
        ),
    ]
