# Generated by Django 6.0.5 on 2026-09-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_classsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending_reschedule', 'Pending reschedule'), ('rescheduled', 'Rescheduled'), ('held_attendance_pending', 'Held — attendance pending'), ('complete_attendance_submitted', 'Complete — attendance submitted'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30),
        ),
    ]
