# Generated by Django 6.0.5 on 2026-09-14 00:03

from django.db import migrations, models


def scheduled_to_pending(apps, schema_editor):
    Attendance = apps.get_model("courses", "Attendance")

    Attendance.objects.filter(
        status="scheduled"
    ).update(
        status="pending"
    )


def pending_to_scheduled(apps, schema_editor):
    Attendance = apps.get_model("courses", "Attendance")

    Attendance.objects.filter(
        status="pending"
    ).update(
        status="scheduled"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_alter_classsession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("attended", "Attended"),
                    ("missed", "Missed"),
                    ("excused", "Excused"),
                ],
                default="pending",
                max_length=30,
            ),
        ),

        migrations.RunPython(
            scheduled_to_pending,
            pending_to_scheduled,
        ),
    ]