# Generated by Django 6.0.5 on 2026-09-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('missed', 'Missed'), ('excused', 'Excused'), ('enrollment_paused', 'Enrollment paused')], default='pending', max_length=30),
        ),
    ]
