# Generated by Django 6.0.5 on 2026-09-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursetimetableslot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='coursetimetableslot',
            constraint=models.UniqueConstraint(fields=('course', 'day_of_week', 'start_time'), name='unique_course_timetable_start'),
        ),
    ]
