# Generated by Django 6.0.5 on 2026-09-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_programme_course_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='programme_icons/'),
        ),
    ]
