# Generated by Django 6.0.5 on 2026-09-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_studentneedsanalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentneedsanalysis',
            options={'verbose_name': 'Student needs analysis', 'verbose_name_plural': 'Student needs analysis'},
        ),
    ]
