# Generated by Django 6.0.5 on 2026-09-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_studentneedsanalysis_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentNeedsAnalysis',
        ),
    ]
