# Generated by Django 6.0.5 on 2026-09-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_delete_studentneedsanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='learning_objective',
        ),
    ]
