# Generated by Django 6.0.5 on 2026-09-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_remove_courseenrollment_learning_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='ended_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
