# Generated by Django 6.0.5 on 2026-09-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_courseenrollment_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended_without_completion', 'Ended without completion'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=30),
        ),
    ]
